version: '3'
services:
  nginx:
    image: nginx:1.19
    container_name: nginx-server
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/sites-enabled/:/etc/nginx/sites-enabled
      - ./:/usr/share/nginx/html
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: php-fpm
    volumes:
      - ./:/usr/share/nginx/html
  mariaDB:
    image: mariadb:10.4
    container_name: mariadb-local
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
  redis:
    image: redis:5.0
    container_name: redis-local
    ports:
      - "6379:6379"
